apiVersion: v1
kind: Pod
metadata:
  name: ebs-test-pod
spec:
  containers:
    - name: app
      image: nginx
      volumeMounts:
        - name: ebs-storage
          mountPath: /usr/share/nginx/html
  volumes:
    - name: ebs-storage
      persistentVolumeClaim:
        claimName: ebs-dynamic-pvc
