apiVersion: v1
kind: Pod
metadata:
  name: web-app-pod
  labels:
    app: frontend
    env: production
spec:
  containers:
  - name: nginx-container
    image: nginx:1.25.3
    ports:
    - containerPort: 80
